'use strict';

// Integration test for POST /api/leads — see MASTER_CHECKLIST.md 5C /
// "Highest-priority single test to add (from 0.5-H)".
//
// Why this uses a real (in-memory) Postgres instead of a mocked db.query():
// the bug this test exists to catch (0.5-H) was a mismatch between the
// columns scripts/migrate.js creates and the columns the controllers actually
// read/write — the kind of bug only a real database can catch, because it's
// Postgres itself that says "column X does not exist," not the JavaScript.
// A test that just fakes db.query() to always succeed would pass even with
// that exact bug still in the code, which defeats the point of having it.
//
// pg-mem (github.com/oguimbal/pg-mem) is a real, in-memory, Postgres-
// compatible SQL engine, used here only as a devDependency for tests — it
// never runs in production and never touches the real database. Each test
// below runs the project's actual scripts/migrate.js against a fresh
// in-memory instance, so the schema these tests check against is never a
// hand-copied guess that could quietly drift from what's really deployed —
// it's generated by the same file that builds the real thing.

const { test, describe, beforeEach, afterEach } = require('node:test');
const assert = require('node:assert');
const express = require('express');
const { newDb } = require('pg-mem');

const DB_MODULE_PATH = require.resolve('../config/database.js');
const LEADS_ROUTER_PATH = require.resolve('../routes/leads.js');
const LEAD_CONTROLLER_PATH = require.resolve('../controllers/leadController.js');
const MIGRATE_PATH = require.resolve('../../scripts/migrate.js');

const VALID_LEAD = {
    name: 'Test Person',
    phone: '07700 900000',
    postcode: 'LS1 1AA',
    service_type: 'Carpet Fitting',
    message: 'This is a test enquiry, not a real customer.',
    gdpr_consent: true,
};

let server;
let pool;

// Builds a brand-new in-memory database, runs the real migration script
// against it, then re-requires the real router fresh so it picks up this
// test's own database instance rather than a previous test's.
async function startTestServer() {
    const mem = newDb({ autoCreateForeignKeyIndices: true });
    const { Pool } = mem.adapters.createPg();
    pool = new Pool();

    const migrate = require(MIGRATE_PATH);
    await migrate(pool);

    delete require.cache[LEAD_CONTROLLER_PATH];
    delete require.cache[LEADS_ROUTER_PATH];
    require.cache[DB_MODULE_PATH] = {
        id: DB_MODULE_PATH,
        filename: DB_MODULE_PATH,
        loaded: true,
        exports: pool,
    };

    const leadsRouter = require(LEADS_ROUTER_PATH);
    const app = express();
    app.use(express.json());
    app.use('/api', leadsRouter);

    return new Promise((resolve) => {
        const s = app.listen(0, () => resolve(s));
    });
}

function baseUrl() {
    return `http://127.0.0.1:${server.address().port}`;
}

describe('POST /api/leads', () => {
    beforeEach(async () => {
        server = await startTestServer();
    });

    afterEach(() => {
        server.close();
    });

    test('accepts a valid submission, returns 201, and writes both the lead and its audit-log entry', async () => {
        const res = await fetch(`${baseUrl()}/api/leads`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(VALID_LEAD),
        });
        const body = await res.json();

        assert.strictEqual(res.status, 201);
        assert.strictEqual(body.success, true);
        assert.ok(body.reference, 'response should include a reference code');

        // Confirm the row actually exists in the database, not just that the
        // HTTP layer reported success.
        const leads = await pool.query('SELECT name, phone, postcode, status FROM leads');
        assert.strictEqual(leads.rows.length, 1);
        assert.strictEqual(leads.rows[0].name, VALID_LEAD.name);
        assert.strictEqual(leads.rows[0].status, 'new');

        // This is the specific assertion that would have caught the 0.5-H
        // bug: it only passes if audit_log actually has the columns the
        // controller writes to (actor, detail).
        const auditRows = await pool.query('SELECT action, actor, detail FROM audit_log');
        assert.strictEqual(auditRows.rows.length, 1);
        assert.strictEqual(auditRows.rows[0].action, 'created');
    });

    test('rejects an invalid submission with 422 and does not create a lead', async () => {
        const res = await fetch(`${baseUrl()}/api/leads`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ ...VALID_LEAD, phone: 'not-a-real-phone-number' }),
        });
        const body = await res.json();

        assert.strictEqual(res.status, 422);
        assert.strictEqual(body.success, false);
        assert.ok(Array.isArray(body.fields));

        const leads = await pool.query('SELECT * FROM leads');
        assert.strictEqual(leads.rows.length, 0, 'an invalid submission must not reach the database');
    });
});
